const mongoose = require('mongoose');
const Students=new mongoose.Schema({
    Student_name:{
        type:String,
        required:true
    },
    Student_DOB:{
        type:Date,
        required:true
    },
    Student_age:{
        type:Number,
        required:true
    },
    Student_roll:{
        type:Number,
        required:true
    },
    Student_email:{
        type:String,
        required:true
    },
    isCurrentStudent:{
        type:Boolean,
        required:true,
        default:true
    }
})
module.exports=mongoose.model('Students',Students)